/* eslint-disable react/prop-types */
import React, { useState } from "react";
import { FaSearch } from "react-icons/fa";
import { getMiniCarSearch } from "../actions/carlist";
const FilterInput = ({
  setSearchCar,
  setShowAllStatusContent,
  setShowNewContent,
  setShowReconditionContent,
  setShowUsedContent,
  setIsSearch,
  setLoading,
}) => {
  const [minPrice, setMinPrice] = useState("");
  const [maxPrice, setMaxPrice] = useState("");
  const [make, setMake] = useState("");
  const [model, setModel] = useState("");

  // Function to handle search button click
  const handleSearch = async (e) => {
    e.preventDefault();
    setLoading(true);

    const searchForm = {
      make,
      model,
    };

    try {
      const result = await getMiniCarSearch({
        params: searchForm,
      });
      setSearchCar(result.cars);
      setShowAllStatusContent(false);
      setShowNewContent(false);
      setShowReconditionContent(false);
      setShowUsedContent(false);
      setIsSearch(true);
      setLoading(false);
      console.log("search result", result);
    } catch (error) {
      console.log("search error", error);
      setLoading(false);
    }
  };

  const modelsByMake = {
    Abarth: [
      "124spider",
      "500",
      "595",
      "595competizione",
      "595esseesse",
      "595pista",
      "595turismo",
      "695",
      "69510thanniversary",
      "695esseesse",
      "695rivale",
      "695yrch",
      "124gt",
      "124rally",
    ],
    AlfaRomeo: [
      "33",
      "145",
      "146",
      "147",
      "149",
      "155",
      "156",
      "159",
      "166",
      "4c",
      "8c",
      "brera",
      "crosswagon",
      "giulia",
      "gt",
      "giulietta",
      "mito",
      "rz",
      "spider",
      "sz",
    ],
    AMG: [
      "a35",
      "a45",
      "amgone",
      "amggt",
      "c43",
      "c63",
      "cls53",
      "e53",
      "e63",
      "g63",
      "gla35",
      "gla45",
      "gls63",
      "gtr",
      "rs3",
      "rs5",
      "rs6",
      "rs7",
      "s3",
      "s4",
      "s5",
    ],
    AstonMartin: [
      "cygnet",
      "db4",
      "db5",
      "db6",
      "db7",
      "db9",
      "db10",
      "db11",
      "dbs",
      "dbsuperleggera",
      "dbr1",
      "dbr2",
      "dbr3",
      "dbr4",
      "dbr5",
      "dbr9",
      "dbrs9",
      "rapide",
      "valhalla",
      "vanquish",
    ],
    Audi: [
      "a1",
      "a3",
      "a4",
      "a6",
      "a7",
      "a8",
      "etron",
      "q2",
      "q3",
      "q4",
      "q5",
      "q7",
      "q8",
      "rs3",
      "rs4",
      "rs5",
      "rs6",
      "rs7",
      "s3",
      "s4",
      "s5",
    ],
    Baic: [
      "a111",
      "a113",
      "a115",
      "a60",
      "a70",
      "a115",
      "arcfox",
      "benben",
      "benbenev",
      "bj20",
      "bj40",
      "bj80",
      "cs15",
      "cs35",
      "cs55",
      "cs75",
      "cs95",
      "cx20",
      "cx30",
      "cx70",
    ],
    Barabus: [
      "2+2",
      "2door",
      "4door",
      "biturbo",
      "cabriolet",
      "convertible",
      "coupe",
      "gtr",
      "lm",
      "lmp",
      "roadster",
      "saloon",
      "sedan",
      "spyder",
      "tkr",
      "twinturbo",
      "v12",
      "v12tt",
      "4c",
      "coupe",
    ],
    Bentley: [
      "arnage",
      "azure",
      "brooklands",
      "bentayga",
      "continentalgt",
      "flyingspur",
      "mulsanne",
      "rturbo",
      "rtype",
      "s1",
      "s2",
      "s3",
      "s4",
      "s5",
      "s6",
      "s7",
      "s8",
      "turbo",
      "t2",
      "mulsanneewb",
    ],
    BMW: [
      "3series",
      "4series",
      "5series",
      "6series",
      "7series",
      "8series",
      "i3",
      "i4",
      "m3",
      "m5",
      "m8",
      "x1",
      "x2",
      "x3",
      "x4",
      "x5",
      "x6",
      "x7",
      "x8",
      "z4",
    ],
    BMWAlpina: [
      "b3",
      "b3s",
      "b4",
      "b4s",
      "b5",
      "b5s",
      "b6",
      "b6s",
      "b7",
      "b8",
      "d3",
      "d4",
      "d5",
      "d6",
      "xd3",
      "xd4",
      "xd5",
      "xd6",
      "b8gran",
      "d3",
    ],
    BYD: [
      "e1",
      "e2",
      "e3",
      "ea1",
      "ea2",
      "ea3",
      "ea4",
      "ea5",
      "ea6",
      "ea7",
      "ea8",
      "ea9",
      "et",
      "et360",
      "et560",
      "etim",
      "etse",
      "etseries",
      "eternity",
      "etphybrid",
    ],
    Cadillac: [
      "ats",
      "ats-v",
      "ct4",
      "ct5",
      "ct6",
      "ctsv",
      "deville",
      "eldorado",
      "escalade",
      "escaladeesv",
      "fleewood",
      "seville",
      "srx",
      "sts",
      "xt4",
      "xt5",
      "xt6",
      "xts",
      "xlr",
      "xt6hybrid",
      "xtshybrid",
    ],
    Changan: [
      "alsvin",
      "benben",
      "benbenmini",
      "cs15",
      "cs35",
      "cs55",
      "cs75",
      "cs95",
      "cx20",
      "cx30",
      "cx40",
      "cx50",
      "cx70",
      "cx75",
      "cs85",
      "cs95",
      "eado",
      "eadoev",
      "eadoxt",
      "cx70t",
      "cv11",
    ],
    Chery: [
      "arrizo3",
      "arrizo5",
      "arrizo7",
      "beta3",
      "crosses",
      "eastar",
      "eastar5",
      "exeedlx",
      "exeedtx",
      "fulwin",
      "fulwin2",
      "karryq",
      "karryyouya",
      "karryyouyou",
      "qq",
      "qqme",
      "tiggo2",
      "tiggo3",
      "tiggo4",
      "tiggo5",
    ],
    Chevrolet: [
      "aveo",
      "blazer",
      "bolt",
      "camaro",
      "captiva",
      "cavalier",
      "colorado",
      "corvette",
      "cruze",
      "equinox",
      "express",
      "malibu",
      "onix",
      "s10",
      "silverado",
      "sonic",
      "spark",
      "suburban",
      "tahoe",
      "trailblazer",
    ],
    Chrysler: [
      "200",
      "300",
      "aspen",
      "concorde",
      "crossfire",
      "grandvoyager",
      "pacifica",
      "ptcruiser",
      "sebring",
      "townandcountry",
    ],
    ChryslerJeep: [
      "cherokee",
      "commander",
      "compass",
      "gladiator",
      "grandcherokee",
      "liberty",
      "patriot",
      "renegade",
      "wrangler",
    ],
    Citroen: [
      "amidship",
      "berlingo",
      "c-elysee",
      "c1",
      "c3",
      "c4",
      "c4cactus",
      "c4grandpicasso",
      "c5",
      "c6",
      "c8",
      "ds3",
      "ds4",
      "ds5",
      "jumper",
      "jumpy",
      "nemo",
      "spacetourer",
      "xantia",
      "xsara",
    ],
    Daf: [
      "33",
      "44",
      "46",
      "55",
      "66",
      "daffodil",
      "marathon",
      "museumkw",
      "museumxf",
      "samuel",
    ],
    Daihatsu: [
      "altis",
      "ayla",
      "beck",
      "cast",
      "ceria",
      "copen",
      "delta",
      "f1",
      "granmax",
      "hijet",
      "materia",
      "mirai",
      "move",
      "sirion",
      "sonica",
      "taft",
      "terios",
      "thor",
      "xenia",
      "yrv",
    ],
    Daimler: [
      "250",
      "astonmartin",
      "ds420",
      "eb110",
      "f-type",
      "f5000",
      "fpace",
      "ftype",
      "i-pace",
      "mkii",
      "mkv",
      "mkx",
      "mkxviii",
      "mkz",
      "mkziii",
      "monaco",
      "montecarlo",
      "pickup",
      "sedan",
      "sportbrake",
    ],
    Dodge: [
      "avenger",
      "caliber",
      "challenger",
      "charger",
      "coronet",
      "dart",
      "demon",
      "durango",
      "journey",
      "magnum",
      "neon",
      "ram",
      "srtviper",
      "stealth",
      "stratus",
      "viper",
      "wc",
      "wc54",
      "wc64",
      "wcseries",
    ],
    DongFeng: [
      "aeolusax3",
      "ax4",
      "ax5",
      "ax7",
      "ax8",
      "ax5ev",
      "joyear",
      "joyearx5",
      "joyearx7",
      "seres",
      "seresev",
      "seresfcv",
      "sereshatch",
      "seresphev",
      "seressedan",
      "seressuv",
      "seresv",
      "seresvf",
      "seresvg",
      "seresvplus",
    ],

    Ferrari: [
      "250",
      "275",
      "288gto",
      "308",
      "328",
      "348",
      "360",
      "456",
      "458",
      "488",
      "512",
      "550",
      "575m",
      "599",
      "612",
      "california",
      "enzo",
      "f12berlinetta",
      "f355",
      "f40",
    ],
    Fiat: [
      "124spider",
      "500",
      "500l",
      "500x",
      "bravo",
      "doblo",
      "ducato",
      "fiorino",
      "freemont",
      "fullback",
      "grande punto",
      "panda",
      "punto",
      "qubo",
      "talento",
      "tipo",
      "ulysse",
      "uno",
      "x1/9",
    ],
    Foton: [
      "cs2",
      "cs3",
      "cs5",
      "cs6",
      "cs35",
      "cs45",
      "cs75",
      "cs85",
      "sauvana",
      "tunland",
    ],
    Gac: [
      "aion",
      "aionlx",
      "enpulse",
      "gn6",
      "gs3",
      "gs4",
      "gs5",
      "gs8",
      "i4",
      "ix4",
      "jax",
      "mbrave",
      "miniev",
      "shenbao",
      "trumpchi",
      "witstar",
    ],
    Gelly: [
      "ge3",
      "gc2",
      "gk5",
      "gs",
      "gs3",
      "gs4",
      "gs5",
      "gs7",
      "gx2",
      "gx5",
    ],
    Genesis: ["g70", "g80", "g90", "gv70", "gv80", "gv90"],
    GMC: [
      "acadia",
      "canyon",
      "sierra1500",
      "sierra2500hd",
      "sierra3500hd",
      "terrain",
      "yukon",
      "yukonxl",
    ],
    GoldenDragon: [
      "xml6117",
      "xml6796",
      "xml6956",
      "xml6129",
      "xml6750",
      "xml6901",
      "xml6950",
      "xml6127",
      "xml6799",
      "xml6958",
    ],
    GreatWall: [
      "c30",
      "c50",
      "coolbear",
      "cowry",
      "hover",
      "havalh1",
      "havalh2",
      "havalh5",
      "havalh6",
      "havalh9",
      "m4",
      "poer",
      "sailor",
      "voleexc10",
      "voleexc20",
      "voleexc30",
      "voleexc50",
      "wingle",
      "wingle5",
      "wingle6",
    ],
    Hino: ["155", "195", "258", "268", "338", "358", "500", "700"],
    Holden: [
      "acrado",
      "aper",
      "astra",
      "barina",
      "captiva",
      "colorado",
      "commodore",
      "equinox",
      "trailblazer",
      "trax",
    ],
    Honda: [
      "accord",
      "amaze",
      "ballade",
      "brio",
      "brv",
      "civic",
      "crv",
      "crz",
      "fitta",
      "fit",
      "grace",
      "hrv",
      "insight",
      "jazz",
      "mobilio",
      "odyssey",
      "pilot",
      "prelude",
      "ridgeline",
      "s2000",
    ],
    Hummer: ["h1", "h2", "h3"],
    Hyundai: [
      "accent",
      "atlas",
      "azera",
      "creta",
      "elana",
      "entourage",
      "equus",
      "genesis",
      "i10",
      "i20",
      "i30",
      "ioniq",
      "kona",
      "palisade",
      "santa fe",
      "sonata",
      "tucson",
      "veloster",
      "venue",
      "veracruz",
    ],
    Infiniti: [
      "qx50",
      "qx60",
      "qx70",
      "qx80",
      "q50",
      "q60",
      "q70",
      "q70l",
      "q30",
      "q40",
    ],
    Iveco: ["daily", "eurocargo", "stralis", "trakker"],
    Jac: [
      "ievan",
      "iex7",
      "seavan",
      "shuailing",
      "refine",
      "refinei",
      "refineiev",
      "ievan",
      "shuailing",
      "seavan",
      "ievan",
      "ievan5",
      "ievan6",
      "ievan7",
      "ievan8",
      "ievan9",
      "ievanplus",
      "ievan7",
      "ievan8",
    ],
    Jaguar: [
      "e-pace",
      "f-pace",
      "f-type",
      "i-pace",
      "s-type",
      "x-type",
      "xe",
      "xf",
      "xj",
      "xk",
    ],
    Jeep: [
      "cherokee",
      "commander",
      "compass",
      "gladiator",
      "grandcherokee",
      "liberty",
      "patriot",
      "renegade",
      "wagoneer",
      "wrangler",
    ],
    Kia: [
      "carens",
      "carnival",
      "ceed",
      "cerato",
      "forte",
      "k5",
      "k900",
      "niro",
      "optima",
      "picanto",
      "quoris",
      "rio",
      "sedona",
      "seltos",
      "sorento",
      "soul",
      "sportage",
      "stinger",
      "stonic",
      "telluride",
    ],
    Kinglong: [
      "c10",
      "c9",
      "c9pl1",
      "c9pl2",
      "c9pl3",
      "c9pl4",
      "c9pl5",
      "c9pl6",
      "c9pl7",
      "c9pl8",
    ],
    Lamborghini: [
      "aventador",
      "countach",
      "diablo",
      "gallardo",
      "huracan",
      "miura",
      "murcielago",
      "sesto",
      "urus",
      "veneno",
    ],
    Lancia: [
      "delta",
      "flaminia",
      "fulvia",
      "gamma",
      "kappa",
      "lybra",
      "musa",
      "phedra",
      "stratos",
      "themav6",
    ],
    LandRover: [
      "defender",
      "discovery",
      "discovery sport",
      "range rover",
      "range rover evoque",
      "range rover sport",
      "range rover velar",
      "series i",
      "series ii",
      "series iii",
      "freelander",
      "lr2",
      "lr3",
      "lr4",
      "range rover classic",
      "range rover phev",
      "range rover sport phev",
      "series iia",
      "series iib",
      "series iic",
    ],
    LeadingIdeal: ["lx", "one", "su1"],
    Lexus: [
      "ct",
      "es",
      "gs",
      "gx",
      "is",
      "lc",
      "ls",
      "lx",
      "nx",
      "rc",
      "rx",
      "ux",
    ],
    Lincoln: [
      "aviator",
      "continental",
      "corsair",
      "marklt",
      "mkc",
      "mks",
      "mkt",
      "mkx",
      "mkz",
      "nautilus",
    ],
    Lotus: ["elan", "elise", "esprit", "evora", "exige"],
    Mg: [
      "3",
      "5",
      "6",
      "7",
      "ezs",
      "gs",
      "hs",
      "mg3",
      "mg5",
      "mg6",
      "mg7",
      "mg8",
      "mgzt",
      "tf",
      "xpower",
      "zr",
      "zs",
      "zsedan",
      "zt",
    ],
    Maserati: ["ghibli", "granturismo", "levante", "quattroporte"],
    Mazda: [
      "2",
      "3",
      "5",
      "6",
      "axela",
      "biante",
      "bt50",
      "cx3",
      "cx4",
      "cx5",
      "cx7",
      "cx8",
      "demio",
      "mazda3",
      "mazda5",
      "mazda6",
      "mx30",
      "mx5",
      "mx6",
      "premacy",
    ],
    Mercedes: [
      "aclass",
      "bclass",
      "cclass",
      "eclass",
      "sclass",
      "gle",
      "glc",
      "gla",
      "glb",
      "gls",
      "cla",
      "classe",
      "sclassmaybach",
      "eqc",
      "slc",
      "sl",
      "gclass",
      "xclass",
      "vclass",
      "marcopolo",
    ],
    Mini: [
      "clubman",
      "convertible",
      "cooper",
      "countryman",
      "coupe",
      "electric",
      "hardtop",
      "jcw",
      "johncooperworks",
      "paceman",
    ],
    Mitsubishi: [
      "3000gt",
      "asx",
      "diamante",
      "eclipsecross",
      "endeavor",
      "evo",
      "fuso",
      "galant",
      "gto",
      "i-miev",
      "l200",
      "lancer",
      "mirage",
      "montero",
      "outlander",
      "pajero",
      "raider",
      "ralliart",
      "spacestar",
      "starion",
    ],
    Mitsuoka: [
      "galue",
      "himiko",
      "le-seyde",
      "like-t3",
      "oroche",
      "rockstar",
      "ryugi",
      "viewt",
    ],
    Morgan: [
      "3wheeler",
      "4",
      "4/4",
      "aero8",
      "plus4",
      "plus6",
      "plus8",
      "roadster",
      "v6",
      "v8",
    ],
    Nio: ["ep7", "es8", "et7", "es6"],
    Nissan: [
      "240sx",
      "370z",
      "altima",
      "armada",
      "frontier",
      "gt-r",
      "juke",
      "kicks",
      "leaf",
      "maxima",
      "murano",
      "nv200",
      "pathfinder",
      "quest",
      "rogue",
      "roguesport",
      "sentra",
      "titan",
      "versa",
      "xtrail",
    ],
    Opel: [
      "adam",
      "amperae",
      "antara",
      "astra",
      "cascada",
      "combo",
      "corsa",
      "crosslandx",
      "grandlandx",
      "gt",
    ],

    Pontiac: [
      "bonneville",
      "firebird",
      "g3",
      "g5",
      "g6",
      "g8",
      "grandam",
      "grandprix",
      "gto",
      "montana",
    ],
    Porsche: [
      "718",
      "911",
      "918",
      "boxster",
      "cayenne",
      "cayman",
      "macan",
      "panamera",
      "taycan",
    ],
    Proton: [
      "exora",
      "inspira",
      "iriz",
      "persona",
      "preve",
      "saga",
      "suprima",
      "x70",
    ],
    Puch: ["mercedesbenzgd", "pinzgauer", "steyr", "v300"],
    Ranger: ["everest", "ranger"],
    Renault: [
      "captur",
      "clio",
      "duster",
      "espace",
      "floride",
      "kadjar",
      "kangoo",
      "koleos",
      "megane",
      "pulse",
      "sandero",
      "scenic",
      "talisman",
      "twingo",
      "zoe",
    ],
    RollsRoyce: ["cullinan", "dawn", "ghost", "phantom", "wraith"],
    Rover: [
      "defender",
      "discovery",
      "discovery sport",
      "freelander",
      "range rover",
      "range rover evoque",
      "range rover sport",
      "velar",
    ],
    Saab: [
      "9-2x",
      "9-3",
      "9-4x",
      "9-5",
      "900",
      "9000",
      "sonett",
      "v4",
      "96",
      "99",
    ],
    Samsung: [
      "sm3",
      "sm5",
      "sm6",
      "sm7",
      "qmx",
      "qm6",
      "qm5",
      "qm3",
      "equate",
      "renaultscala",
    ],
    Saic: [
      "mg3",
      "mg5",
      "mg6",
      "mg7",
      "mg8",
      "mgzt",
      "eroe",
      "maxusd60",
      "maxusd90",
      "maxusev80",
    ],
    Scania: [
      "a30",
      "g440",
      "k124",
      "k230",
      "k270",
      "k280",
      "k310",
      "k320",
      "k360",
      "k370",
      "k380",
      "k400",
      "k410",
      "k420",
      "k440",
      "k450",
      "k460",
      "k470",
      "k480",
      "k490",
    ],
    Seat: ["alhambra", "arona", "ateca", "ibiza", "leon", "mii", "tarraco"],
    Sera: ["sera"],
    Shuanghuan: ["bubble", "ceo", "sceo"],
    SinoTruck: ["howo", "steed"],
    Smart: ["eqfortwo", "eqforfour", "fortwo", "roadster"],
    Ssangyong: [
      "actyon",
      "chairman",
      "korando",
      "kyron",
      "musso",
      "rexton",
      "rodius",
      "tivoli",
      "xlv",
    ],
    Subaru: [
      "ascent",
      "baja",
      "brz",
      "chiffon",
      "crosstrek",
      "dex",
      "forester",
      "impreza",
      "justy",
      "legacy",
      "lucra",
      "outback",
      "r1",
      "r2",
      "sambar",
      "stella",
      "svx",
      "tribeca",
      "wrx",
      "xt",
    ],
    Suzuki: [
      "alto",
      "apv",
      "baleno",
      "carry",
      "celerio",
      "ciaz",
      "dzire",
      "ertiga",
      "escudo",
      "every",
      "grandvitara",
      "ignis",
      "jimny",
      "karimun",
      "kizashi",
      "lapin",
      "liana",
      "mrwagon",
      "palette",
      "solio",
    ],
    Tesla: [
      "model s",
      "model 3",
      "model x",
      "model y",
      "cybertruck",
      "roadster",
      "model 3 long range",
      "model s plaid",
      "model x plaid",
      "model s long range",
      "model y long range",
      "model 3 standard range plus",
      "model 3 performance",
      "model s performance",
      "model x long range",
      "model x performance",
      "model y performance",
      "model y standard range plus",
    ],
    Toyota: [
      "4runner",
      "86",
      "allex",
      "allion",
      "alphard",
      "avalon",
      "camry",
      "corolla",
      "highlander",
      "landcruiser",
      "prius",
      "rav4",
      "sienna",
      "tacoma",
      "tundra",
    ],
    Ud: ["condor", "quester", "quon"],
    Venucia: ["d50", "r50", "t60", "t70", "vx25", "xing", "zhang"],
    Voyah: [
      "espresso1",
      "espresso2",
      "espresso3",
      "espresso4",
      "espresso5",
      "im8",
      "im9",
      "m100",
      "m200",
      "m300",
    ],
    Volkswagen: [
      "amarok",
      "arteon",
      "beetle",
      "corrado",
      "golf",
      "id4",
      "jetta",
      "kombi",
      "passat",
      "phaeton",
      "polo",
      "scirocco",
      "sharan",
      "teramont",
      "tiguan",
      "touran",
      "touareg",
      "troc",
      "up",
      "golf",
    ],
    Volvo: [
      "s60",
      "s90",
      "v60",
      "v90",
      "xc40",
      "xc60",
      "xc90",
      "c30",
      "v40",
      "v50",
      "v70",
      "xc70",
      "s40",
      "xc50",
      "s40",
      "v40crosscountry",
      "v60crosscountry",
      "v90crosscountry",
      "xc60hybrid",
      "xc90hybrid",
    ],
  };

  const handleMakeChange = (e) => {
    setMake(e.target.value);
    setModel("");
  };
  return (
    <div className="p-6 lg:p-9  bg-[#202f3d79] rounded-lg flex flex-col lg:flex-row justify-center gap-3 items-center ">
      <div className="flex flex-col lg:flex-row justify-center items-center gap-3 w-full">
        <div className="flex flex-col  items-start text-black   w-full gap-4">
          <p className="text-[#aec1cc]">Make</p>
          <div className="text-[#d1d6d8] flex flex-col justify-start items-start w-full gap-2">
            <select
              className="select select-bordered w-full border-2 rounded-lg py-3 px-2"
              style={{ backgroundColor: "hsl(244, 20%, 14%)" }}
              value={make}
              onChange={handleMakeChange}
            >
              <option value="" disabled defaultValue>
                Select Make
              </option>
              <option value="Toyota">Toyota</option>
              <option value="Suzuki">Suzuki</option>
              <option value="Nissan">Nissan</option>
              <option value="Honda">Honda</option>
              <option value="Daihatsu">Daihatsu</option>
              <option value="Mazda">Mazda</option>
              <option value="Subaru">Subaru</option>
              <option value="Mitsubishi">Mitsubishi</option>
              <option value="BMW">BMW</option>
              <option value="Volkswagen">Volkswagen</option>
              <option value="Audi">Audi</option>
              <option value="Volvo">Volvo</option>
              <option value="Fiat">Fiat</option>
              <option value="Mercedes">Mercedes</option>
              <option value="Peugeot">Peugeot</option>
              <option value="Land Rover">Land Rover</option>
              <option value="Lexus">Lexus</option>
              <option value="Ford">Ford</option>
              <option value="Isuzu">Isuzu</option>
              <option value="Renault">Renault</option>
              <option value="Porsche">Porsche</option>
              <option value="Citroen">Citroen</option>
              <option value="Alfa Romeo">Alfa Romeo</option>
              <option value="Mini">Mini</option>
              <option value="Chrysler Jeep">Chrysler Jeep</option>
              <option value="Abarth">Abarth</option>
              <option value="Jaguar">Jaguar</option>
              <option value="Maserati">Maserati</option>
              <option value="Daf">Daf</option>
              <option value="Hino">Hino</option>
              <option value="Mitsuoka">Mitsuoka</option>
              <option value="Scania">Scania</option>
              <option value="Rover">Rover</option>
              <option value="Man">Man</option>
              <option value="Chrysler">Chrysler</option>
              <option value="Aston Martin">Aston Martin</option>
              <option value="Lotus">Lotus</option>
              <option value="Amg">Amg</option>
              <option value="Bentley">Bentley</option>
              <option value="Bmw Alpina">Bmw Alpina</option>
              <option value="Iveco">Iveco</option>
              <option value="Chevrolet">Chevrolet</option>
              <option value="Mg">Mg</option>
              <option value="Hyundai">Hyundai</option>
              <option value="Dodge">Dodge</option>
              <option value="Kia">Kia</option>
              <option value="Opel">Opel</option>
              <option value="Rolls Royce">Rolls Royce</option>
              <option value="Ferrari">Ferrari</option>
              <option value="Lamborghini">Lamborghini</option>
              <option value="Smart">Smart</option>
              <option value="Saab">Saab</option>
              <option value="Morgan">Morgan</option>
              <option value="Cadillac">Cadillac</option>
              <option value="Sino Truck">Sino Truck</option>
              <option value="Changan">Changan</option>
              <option value="Infiniti">Infiniti</option>
              <option value="Gelly">Gelly</option>
              <option value="Xpeng">Xpeng</option>
              <option value="Ud">Ud</option>
              <option value="Daimler">Daimler</option>
              <option value="Genesis">Genesis</option>
              <option value="Ssangyong">Ssangyong</option>
              <option value="Jeep">Jeep</option>
              <option value="Chery">Chery</option>
              <option value="Byd">Byd</option>
              <option value="Buick">Buick</option>
              <option value="Hummer">Hummer</option>
              <option value="Tesla">Tesla</option>
              <option value="Lincoln">Lincoln</option>
              <option value="Faw">Faw</option>
              <option value="Great Wall">Great Wall</option>
              <option value="Baic">Baic</option>
              <option value="Leading Ideal">Leading Ideal</option>
              <option value="Dong Feng">Dong Feng</option>
              <option value="Gac">Gac</option>
              <option value="Gmc">Gmc</option>
              <option value="Saic">Saic</option>
              <option value="Lancia">Lancia</option>
              <option value="Jac">Jac</option>
              <option value="Europe Ford">Europe Ford</option>
              <option value="Pontiac">Pontiac</option>
              <option value="Samsung">Samsung</option>
              <option value="Foton">Foton</option>
              <option value="Golden Dragon">Golden Dragon</option>
              <option value="Autobianchi">Autobianchi</option>
              <option value="Kinglong">Kinglong</option>
              <option value="Leapmotor">Leapmotor</option>
              <option value="Nio">Nio</option>
              <option value="Venucia">Venucia</option>
              <option value="Voyah">Voyah</option>
              {/* Add other makes here */}
            </select>
          </div>
        </div>
        <div className="flex flex-col  items-start text-black   w-full gap-4">
          <p className="text-[#aec1cc]">Model</p>

          <div className="text-[#d1d6d8] flex flex-col justify-start items-start w-full gap-2">
            <select
              className="select select-bordered w-full border-2 rounded-lg py-3 px-2"
              style={{ backgroundColor: "hsl(244, 20%, 14%)" }}
              value={model}
              onChange={(e) => setModel(e.target.value)}
              disabled={!make}
            >
              <option value="" disabled defaultValue>
                {make ? `Select ${make}'s Models` : "Select Models"}
              </option>
              {make &&
                modelsByMake[make].map((carModel) => (
                  <option key={carModel} value={carModel}>
                    {carModel}
                  </option>
                ))}
            </select>
          </div>
        </div>
      </div>
      <div className="flex flex-col justify-start items-start w-full gap-2 ">
        <div className="flex flex-col  items-start text-black   w-full gap-4">
          <p className="text-[#aec1cc] ">Price</p>
          <div className="flex flex-col lg:flex-row gap-3  w-full">
            <input
              className="border-2  w-full  rounded-lg px-2 text-[#aec1cc]  py-3"
              style={{ backgroundColor: "hsl(244, 20%, 14%)" }}
              type="number"
              name="minPrice"
              value={minPrice}
              placeholder="Min Price"
              onChange={(e) => setMinPrice(e.target.value)}
            />
            <input
              className="border-2    rounded-lg px-2 text-[#aec1cc]  py-3"
              style={{ backgroundColor: "hsl(244, 20%, 14%)" }}
              type="number"
              name="maxPrice"
              value={maxPrice}
              placeholder="Max Price"
              onChange={(e) => setMaxPrice(e.target.value)}
            />
            <button
              className="p-3  bg-[#dee5ec79] text-white rounded-lg px-7 flex flex-row  justify-between gap-3 items-center"
              onClick={handleSearch}
            >
              {" "}
              <FaSearch />
              Search
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FilterInput;
